### ISSUE TITLE
No build files

### ISSUE THREAD

**Issue by wuangyalin** [ShaharLahav/ionic2-threejs#1]
http://localhost:8100/build/js/angular2-polyfills.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/js/app.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/js/angular2-polyfills.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/js/app.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by ShaharLahav** [comment]
Thank you, but the program works right?
